<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Admin</th>
      <th>Email</th>
      <th>Password</th>
    </tr>
  </thead>
  <tbody>
    @foreach($users as $user)
    <tr>
      <td>{{$user->id}}</td>
      <td>{{$user->name}}</td>
      <td>{{$user->admin}}</td>
      <td>{{$user->email}}</td>
      <td>{{$user->password}}</td>
    </tr>
    @endforeach
  </tbody>
</table>
